name: Health Score
description: Compute a repository health score from tests, docs, security, dead code and CI reliability.
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  coverage_path:
    description: 'Optional path to coverage XML (coverage.py XML) or lcov'
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install tools
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install coverage xmltodict vulture bandit requests
    - name: Run health score
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        COVERAGE_PATH: ${{ inputs.coverage_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        python .github/actions/health-score/compute_score.py
      # Capture outputs (composite actions cannot set outputs directly from steps; we'll write a file)
